
platform :ios, '8.0'

target 'LBXScanDemo' do


#pod 'LBXScan/All', path:"../"
#pod 'LBXScan/LBXZBar', path:"../"
pod 'LBXScan/LBXNative', path:"../"
pod 'LBXScan/LBXZXing', path:"../"
pod 'LBXScan/UI', path:"../"
#pod 'LBXZBarSDK', git:"https://github.com/MxABC/LBXZBarSDK.git"
pod 'LBXScan/LBXZBar', path:"../"
pod 'Toast', '~> 4.0.0'

pod 'ZXingObjC', :git => 'https://github.com/zxingify/zxingify-objc.git', :tag => '3.6.7'

end






